const totalPages=32;
const pages=['assets/images/chapter-01/page-01.webp','assets/images/chapter-01/page-02.webp','assets/images/chapter-01/page-03.webp','assets/images/chapter-01/page-04.webp','assets/images/chapter-01/page-05.webp','assets/images/chapter-01/page-06.webp','assets/images/chapter-01/page-07.webp','assets/images/chapter-01/page-08.webp','assets/images/chapter-01/page-09.webp','assets/images/chapter-01/page-10.webp','assets/images/chapter-01/page-11.webp','assets/images/chapter-01/page-12.webp','assets/images/chapter-01/page-13.webp','assets/images/chapter-01/page-14.webp','assets/images/chapter-01/page-15.webp','assets/images/chapter-01/page-16.webp','assets/images/chapter-01/page-17.webp','assets/images/chapter-01/page-18.webp','assets/images/chapter-01/page-19.webp','assets/images/chapter-01/page-20.webp','assets/images/chapter-01/page-21.webp','assets/images/chapter-01/page-22.webp','assets/images/chapter-01/page-23.webp','assets/images/chapter-01/page-24.webp','assets/images/chapter-01/page-25.webp','assets/images/chapter-01/page-26.webp','assets/images/chapter-01/page-27.webp','assets/images/chapter-01/page-28.webp','assets/images/chapter-01/page-29.webp','assets/images/chapter-01/page-30.webp','assets/images/chapter-01/page-31.webp','assets/images/chapter-01/page-32.webp'];

/*
 Guion accesible completo para las páginas ilustradas 1–24.
 Incluye descripción de cada viñeta/acción y todos los textos hablados del guion técnico.
 Las páginas 8–14 fueron sincronizadas con las ilustraciones actualizadas.
*/
const scripts=[
[{s:"TÍTULO",t:"TECH GUARDIANS — EL CÓDIGO DEL MUNDO. CAPÍTULO 1: EL DÍA QUE EL MUNDO SE DETUVO."},{s:"NARRADOR",t:"Año 2045."},{s:"NARRADOR",t:"El mundo no depende de una sola máquina."},{s:"NARRADOR",t:"Depende de millones de sistemas que aprendieron a trabajar juntos."},{s:"NEXUS",t:"Infraestructura digital internacional. Conectando personas, sistemas y oportunidades en todo el mundo."},{s:"HOSPITALES",t:"Tecnología que mejora la atención médica y salva vidas."},{s:"TRANSPORTE",t:"Ciudades más conectadas y un mundo en movimiento."},{s:"UNIVERSIDADES",t:"Conocimiento sin fronteras para nuevas generaciones."},{s:"EMPRESAS",t:"Innovación que impulsa soluciones para un futuro más sostenible."},{s:"HOGARES",t:"La tecnología nos acerca a las personas que más importan."},{s:"NARRADOR",t:"NEXUS está presente en cada aspecto de nuestra vida. Hace posible que todo funcione de manera más eficiente, segura e inclusiva."},{s:"NARRADOR",t:"Gracias a la tecnología, el mundo está más conectado que nunca."},{s:"PANTALLA",t:"NEXUS NODE 07. SYNC 99.98 %. Una lectura desciende brevemente a 99.41 % mientras el resto permanece estable."}],
[{s:"NARRADOR",t:"Ciudades. Universidades. Hospitales. Transporte. Comunicaciones. Empresas."},{s:"NARRADOR",t:"Cada día, millones de personas utilizan servicios que trabajan juntos a través de NEXUS."},{s:"NARRADOR",t:"NEXUS conecta servicios que casi nadie nota... mientras funcionan."},{s:"NARRADOR",t:"Diferentes lugares. Un mismo propósito. Un mundo que funciona para las personas."},{s:"TRANSPORTE",t:"Las personas se mueven por la ciudad de forma más rápida, segura y conectada."},{s:"PANTALLA",t:"NEXUS TRANSIT. Identidad validada. Ruta confirmada. Sincronización activa."},{s:"HOSPITALES",t:"La tecnología permite una atención médica más precisa, oportuna y humana."},{s:"PANTALLA",t:"Expediente clínico sincronizado con NEXUS. Sincronización normal."},{s:"UNIVERSIDADES",t:"El conocimiento no tiene fronteras. Estudiantes y docentes de diferentes países colaboran en tiempo real."},{s:"PANTALLA",t:"Conexión global estable."},{s:"EMPRESAS",t:"La logística y la producción se mantienen en movimiento gracias a sistemas automatizados e inteligentes."},{s:"PANTALLA",t:"Centro logístico: recepción, clasificación, rutas optimizadas y envío. Ruta de paquete recalculada."},{s:"NARRADOR",t:"NEXUS integra ciudades, sistemas, organizaciones y personas en todo el mundo. Millones de servicios trabajan juntos para que la vida siga avanzando."},{s:"NARRADOR",t:"NEXUS conecta servicios que casi nadie nota... mientras funcionan."},{s:"PANTALLA",t:"TRANSIT: operación estable, SYNC +0.8 s. HEALTH: datos sincronizados, SYNC +1.0 s. EDU: conexión global, SYNC +0.7 s. LOGISTICS: operación normal, ruta recalculada."}],
[{s:"NARRADOR",t:"En algún lugar del mundo, un centro de operaciones monitorea en tiempo real los servicios de NEXUS. Todo funciona con normalidad."},{s:"PANTALLA",t:"NEXUS — Infraestructura digital internacional. Sistemas totales: 1,482. 99.98 % en línea. Tráfico global: 24.7 Tbps. Latencia promedio: 182 ms. Servicios globales: operativos."},{s:"NARRADOR",t:"Un pequeño indicador cambia de verde a amarillo."},{s:"PANTALLA",t:"África — Nube y datos — 280 ms — ALERTA. Latencia normal: 80–150 ms. Estado: latencia elevada."},{s:"OPERADOR",t:"Latencia de 280 milisegundos. Probablemente un nodo saturado."},{s:"OPERADOR",t:"No hay otros servicios afectados. Seguimos monitoreando."},{s:"NARRADOR",t:"El indicador vuelve a verde."},{s:"OPERADOR",t:"Resuelto. La latencia volvió a los valores normales."},{s:"OPERADOR",t:"Parece que fue una sobrecarga temporal."},{s:"NARRADOR",t:"La primera anomalía duró menos de cuatro segundos."},{s:"NARRADOR",t:"Un evento pequeño. Apenas un cambio en la latencia. Nada más... por ahora."}],
[{s:"NARRADOR",t:"Una aplicación de transporte muestra una ruta normal."},{s:"USUARIA",t:"Perfecto. Llego a tiempo."},{s:"PANTALLA",t:"NEXUS TRANSIT. Origen: Mi ubicación. Destino: Centro de la ciudad. 25 min. 8.4 km."},{s:"NARRADOR",t:"La ruta cambia repentinamente a un destino imposible."},{s:"USUARIA",t:"¿Qué...?"},{s:"PANTALLA",t:"Destino: Base Orbital - Estación 1. Ruta no disponible para transporte terrestre."},{s:"NARRADOR",t:"La pantalla se corrige sola."},{s:"USUARIA",t:"Debí tocar algo."},{s:"PANTALLA",t:"Destino: Centro de la ciudad. 25 min. 8.4 km."},{s:"NARRADOR",t:"En segundo plano, otro usuario observa el mismo comportamiento."},{s:"USUARIO",t:"¿Eh...? ¿Qué fue eso?"},{s:"PANTALLA",t:"Destino: Estación Lunar - Alpha. Ruta no disponible para transporte terrestre."},{s:"NARRADOR",t:"La segunda fue fácil de ignorar. Un error extraño. Una ruta imposible. Se corrigió sola en segundos."},{s:"NARRADOR",t:"Pequeñas anomalías pueden parecer coincidencias... hasta que dejan de serlo."},{s:"NARRADOR",t:"Para la mayoría de las personas, solo fue un momento confuso en un día normal."},{s:"NARRADOR",t:"Todo funciona. Aún..."},{s:"NARRADOR",t:"Millones de personas siguen usando la tecnología sin saber que, en algún lugar, algo más grande está comenzando."},{s:"NARRADOR",t:"Un mundo conectado. Un mismo propósito. Una historia que apenas comienza."}],
[{s:"RÓTULO",t:"AKIRA — Desarrollo de software."},{s:"NARRADOR",t:"En la sala de desarrollo, el equipo analiza una de las primeras anomalías."},{s:"PANTALLA",t:"NEXUS — API Movilidad. Solicitudes por minuto: 12,480. Latencia: 183 ms. Disponibilidad: 99.97 %."},{s:"NOAH",t:"La API de movilidad devolvió respuestas inconsistentes."},{s:"PANTALLA",t:"Respuestas inconsistentes: solicitudes /routes alternan datos válidos, destino inválido y coordenadas inválidas, aun con estado 200."},{s:"AKIRA",t:"¿Cambió el contrato?"},{s:"AKIRA",t:"No. El código desplegado coincide con el repositorio."},{s:"PANTALLA",t:"Repositorio remoto: código sincronizado, sin diferencias. Entorno de producción: misma versión desplegada."},{s:"AKIRA",t:"Entonces... ¿por qué respondió algo que nadie programó?"},{s:"PANTALLA",t:"Logs de respuesta de producción muestran destinos inesperados como Base Orbital y Estación Lunar entre respuestas normales."},{s:"NARRADOR",t:"Todo indica que las respuestas provienen del mismo sistema. Con solicitudes válidas. Desde usuarios reales. Y el código no muestra modificaciones."},{s:"NARRADOR",t:"Algo está generando resultados que no deberían existir."},{s:"NARRADOR",t:"La tecnología funciona... Pero ahora, algo no encaja."},{s:"NARRADOR",t:"Y es solo el comienzo."}],
[{s:"RÓTULO",t:"AKIRA — Desarrollo de software."},{s:"NARRADOR",t:"Akira ejecuta pruebas locales para validar el sistema."},{s:"PANTALLA",t:"PRUEBAS LOCALES. Compilación OK. Pruebas unitarias OK. Integración OK. API - Movilidad OK. API - Usuarios OK. API - Rutas OK. Base de datos OK. Servicios externos OK. 128 pruebas - 128 correctas. TODO CORRECTO."},{s:"AKIRA",t:"Funciona aquí."},{s:"NARRADOR",t:"Pero en el monitoreo remoto, la situación es diferente."},{s:"PANTALLA",t:"TELEMETRÍA GLOBAL - API MOVILIDAD. Se observan picos anómalos de latencia en distintas regiones."},{s:"AKIRA",t:"Pero no allá."},{s:"NARRADOR",t:"Akira marca uno de los eventos para analizarlo en detalle."},{s:"PANTALLA",t:"Detalle del evento. Servicio: API Movilidad. Región: Sudamérica. Inicio: 02:17:43.125 UTC. Fin: 02:17:47.083 UTC. Duración: 3.96 segundos. Latencia máxima: 780 ms. Estado: recuperado automáticamente."},{s:"AKIRA",t:"02:17:43... cuatro segundos."},{s:"NARRADOR",t:"Poco después, aparece un evento similar en otra región."},{s:"PANTALLA",t:"Eventos similares: Europa 4.01 s; Asia 3.98 s; Sudamérica 3.96 s; Norteamérica 4.00 s."},{s:"AKIRA",t:"¿La misma duración?"},{s:"NARRADOR",t:"Un mismo patrón. Múltiples regiones. La misma duración. Esto ya no parece una coincidencia."},{s:"NARRADOR",t:"Algo está ocurriendo. Y se repite en todo el mundo."},{s:"CIERRE",t:"La investigación continúa..."}],
[{s:"RÓTULO",t:"MAYA — Quality Engineer."},{s:"NARRADOR",t:"Maya realiza pruebas en un entorno de calidad para validar el comportamiento de la aplicación en diferentes dispositivos, regiones y condiciones."},{s:"PANTALLA",t:"ENTORNO DE PRUEBAS - NEXUS APP. Dispositivos: móvil, tablet, web y Smart TV. Configuraciones: región global, idioma español, conexión Wi-Fi / 4G / 5G, usuario estándar / premium y datos reales / anónimos."},{s:"NARRADOR",t:"Una de las pruebas se ejecuta correctamente."},{s:"TÉCNICO",t:"Ya pasó. Podemos cerrar el incidente."},{s:"PANTALLA",t:"PRUEBA EXITOSA. Inicio de sesión, búsqueda de ruta, cálculo de tiempo, pago simulado y notificaciones: 5/5 correctas."},{s:"MAYA",t:"Una ejecución correcta no demuestra que el problema desapareció."},{s:"NARRADOR",t:"Maya cambia las condiciones de la prueba para explorar más escenarios."},{s:"MAYA",t:"Cambiemos las condiciones."},{s:"PANTALLA",t:"Configurar prueba: región Japón, idioma inglés, red móvil 4G, usuario nuevo y cuenta real anonimizada. Se ejecutan pruebas en iOS Japón, Android EE. UU., Web Alemania y Tablet Brasil."},{s:"NARRADOR",t:"La aplicación devuelve información contradictoria."},{s:"PANTALLA",t:"iOS - Japón: destino Estación Central, 28 min, 12.4 km. Android - EE. UU.: destino Aeropuerto Internacional, 3 h 12 min, 286 km, ruta inusual detectada. Web - Alemania: destino Estación Central, 26 min, 11.8 km. Tablet - Brasil: destino Base Orbital - Alpha, 6 h 38 min, 402 km, ruta no disponible para transporte terrestre."},{s:"MAYA",t:"Ahí estás. El mismo servicio. Respuestas diferentes según la región."},{s:"MAYA",t:"Esto no es un error aleatorio. El comportamiento cambia con ciertas condiciones. Alguien está manipulando las respuestas."},{s:"PANTALLA",t:"Registro de pruebas: Japón correcto; EE. UU. inconsistente; Alemania correcto; Brasil inconsistente; Singapur inconsistente. Patrón detectado: mismas ventanas de tiempo, múltiples regiones, respuestas contradictorias y mismo servicio — API Movilidad."},{s:"NARRADOR",t:"No es un problema de un dispositivo. Es un patrón global."}],
[{s:"TÍTULO",t:"PÁGINA 8 — REPRODUCIENDO EL PROBLEMA."},{s:"NARRADOR",t:"Maya recopila evidencia del comportamiento anómalo en diferentes regiones y condiciones."},{s:"PANTALLA",t:"REGISTRO DEL EVENTO. Usuario: u_45821, válido. Región: Singapur. Conexión: inestable (4G). Dispositivo: Android. Hora UTC: 02:17:43. Comportamiento anómalo detectado. Logs: auth user valid; network unstable; region SG; response inconsistent_data."},{s:"MAYA",t:"Entrada: usuario válido. Red inestable. Región distinta."},{s:"NARRADOR",t:"Compara los resultados con lo que se espera y documenta las diferencias."},{s:"PANTALLA",t:"CASO DE PRUEBA #27. Esperado: información sincronizada, datos consistentes y misma respuesta en todas las regiones. Obtenido: dos estados incompatibles, información diferente según la región y respuesta fuera de lo esperado."},{s:"MAYA",t:"Esperado: información sincronizada. Obtenido: dos estados incompatibles."},{s:"NARRADOR",t:"El técnico revisa el mismo evento en su entorno de monitoreo."},{s:"NOAH",t:"¿Es el mismo fallo?"},{s:"PANTALLA",t:"COMPARACIÓN DE RESULTADOS. Nueva York: estado Estación Central, tiempo 28 min, latencia 120 ms, respuesta normal. Singapur: estado Base Orbital - Alpha, tiempo 3 h 12 min, latencia 780 ms, respuesta inconsistente."},{s:"MAYA",t:"Todavía no lo sé."},{s:"NARRADOR",t:"Maya continúa ajustando las condiciones para reproducir el comportamiento."},{s:"PANTALLA",t:"CONFIGURACIÓN DE PRUEBA. Región: Brasil. Idioma: Portugués. Conexión: Red móvil (4G). Tipo de usuario: Estándar. Datos de prueba: Cuenta real anonimizada."},{s:"PANTALLA",t:"RESULTADO DE LA PRUEBA: INFORMACIÓN CONTRADICTORIA. App móvil: destino Centro de la ciudad, 26 min, 11.8 km. API/Servidor: destino Estación Lunar - Alpha, 6 h 42 min, 384,400 km."},{s:"MAYA",t:"Pero ya sé cómo hacerlo aparecer."},{s:"NARRADOR",t:"El patrón se reproduce en distintas regiones y con diferentes condiciones."},{s:"PANTALLA",t:"EVENTOS RECIENTES. Europa 4.01 s; Asia 3.98 s; Sudamérica 3.96 s; Norteamérica 4.00 s; Medio Oriente 3.97 s."},{s:"NARRADOR",t:"Ya no parece una coincidencia. Hay un patrón."},{s:"PANTALLA",t:"MISMO COMPORTAMIENTO. MISMA DURACIÓN. DIFERENTES REGIONES. ≈ 4 SEGUNDOS."},{s:"NARRADOR",t:"Maya ha encontrado cómo reproducir la anomalía. Ahora el equipo puede seguir investigando."},{s:"NARRADOR",t:"La pregunta ya no es si ocurre... sino por qué."}],
[{s:"TÍTULO",t:"PÁGINA 9 — BUSCANDO EL PATRÓN EN LOS DATOS."},{s:"NARRADOR",t:"Leo analiza grandes volúmenes de datos para encontrar un patrón entre los eventos registrados en las últimas horas."},{s:"PANTALLA",t:"ANÁLISIS GLOBAL DE EVENTOS — Últimas 12 horas (UTC). Eventos totales: 12,438. Regiones afectadas: 42. Sectores: transporte, salud, educación, finanzas, comunicaciones, gobierno, servicios en la nube y otros."},{s:"NARRADOR",t:"El modelo de IA agrupa los eventos por similitud de comportamiento."},{s:"LEO",t:"Busca correlaciones entre los eventos de las últimas doce horas."},{s:"PANTALLA",t:"AGRUPACIÓN DE ANOMALÍAS (IA). Grupos por transporte, educación, salud, finanzas, servicios en la nube, comunicaciones y otros. Similitud de comportamiento y patrón temporal."},{s:"NARRADOR",t:"Los resultados muestran eventos en distintos sectores, sin conexión aparente entre las aplicaciones."},{s:"PANTALLA",t:"EVENTOS SELECCIONADOS: 02:16:58 Europa Transporte — Retraso en rutas; 02:17:12 Asia Educación — Error en plataforma; 02:17:43 Sudamérica Salud — Acceso intermitente; 02:18:21 Norteamérica Finanzas — Transacción rechazada; 02:19:05 Medio Oriente Comunicaciones — Desconexión temporal; 02:20:11 Europa Servicios en la nube — Latencia elevada."},{s:"LEO",t:"Transporte, educación, salud... no comparten aplicación."},{s:"NARRADOR",t:"Leo amplía el análisis para encontrar el elemento común entre todos los eventos."},{s:"LEO",t:"Entonces busquemos qué sí comparten."},{s:"PANTALLA",t:"ANÁLISIS DE CAUSA COMÚN: transporte, educación, salud, finanzas, comunicaciones, gobierno, nube y datos convergen en INFRAESTRUCTURA DE RED GLOBAL."},{s:"PANTALLA",t:"FACTORES COMUNES: misma ventana de tiempo; mismas rutas de red; mismos proveedores de infraestructura; dependencia de servicios en la nube; patrón de latencia anómalo."},{s:"LEO",t:"Aquí está. Todos dependen de la misma infraestructura."},{s:"PANTALLA",t:"NEXUS — INFRAESTRUCTURA DIGITAL INTERNACIONAL."},{s:"NARRADOR",t:"No es un problema de una sola aplicación ni de un sector. El origen está en la infraestructura que conecta todo."},{s:"NARRADOR",t:"Ahora que sabemos qué comparten los eventos, podemos definir la estrategia de respuesta."},{s:"CIERRE",t:"CONTINÚA... PÁGINA 10."}],
[{s:"TÍTULO",t:"PÁGINA 10 — DEL ANÁLISIS A LA ACCIÓN."},{s:"NARRADOR",t:"Leo analiza la relación entre los incidentes y los servicios conectados a NEXUS."},{s:"PANTALLA",t:"SERVICIOS CONECTADOS A NEXUS: Transporte, Salud, Educación, Finanzas, Comunicaciones, Energía y Servicios en la nube."},{s:"PANTALLA",t:"LÍNEA DE TIEMPO DE INCIDENTES: múltiples sectores muestran eventos dentro de una misma ventana temporal."},{s:"LEO",t:"Todos consultaron infraestructura distribuida en la misma ventana temporal."},{s:"NARRADOR",t:"Un compañero propone una posible causa."},{s:"NOAH",t:"¿Ataque?"},{s:"LEO",t:"Demasiado pronto. Todavía necesitamos más evidencia."},{s:"NARRADOR",t:"Leo alimenta el modelo con más datos para buscar patrones más profundos."},{s:"PANTALLA",t:"ANÁLISIS CON IA: registros de solicitudes, eventos de red, trazas de servicios, métricas de infraestructura, datos de múltiples regiones y correlación temporal."},{s:"LEO",t:"Una correlación no es una causa. Necesitamos más datos."},{s:"NARRADOR",t:"El modelo revela un patrón inesperado en los datos combinados."},{s:"PANTALLA",t:"PATRÓN DETECTADO — Análisis de correlación multidimensional. Servicios involucrados: Transporte, Salud, Educación, Finanzas, Comunicaciones, Energía, Nube y datos. Ventana temporal común ≈ 4 segundos."},{s:"PANTALLA",t:"CORRELACIÓN ENTRE SERVICIOS: matriz con correlación alta entre múltiples servicios."},{s:"LEO",t:"Pero esto... no parece ruido."},{s:"PANTALLA",t:"DETALLE DEL PATRÓN. Duración: 3.96 segundos. Afecta a múltiples servicios. Misma forma en diferentes regiones."},{s:"NARRADOR",t:"El mismo patrón se repite en distintas regiones y servicios, todos conectados a través de NEXUS."},{s:"NARRADOR",t:"No es un incidente aislado. Es un comportamiento global, coordinado y preciso."},{s:"NARRADOR",t:"Ahora que sabemos qué comparten los eventos, podemos definir la estrategia de respuesta."},{s:"CIERRE",t:"CONTINÚA... PÁGINA 11."}],
[{s:"TÍTULO",t:"PÁGINA 11 — CIBERSEGURIDAD: MÁS ALLÁ DE LO EVIDENTE."},{s:"NARRADOR",t:"Hana revisa el tráfico de red en el centro de ciberseguridad para buscar indicios de intrusión."},{s:"PANTALLA",t:"MONITOREO DE TRÁFICO - NEXUS. Transporte, Salud, Educación, Finanzas, Comunicaciones, Energía y Nube y datos: Normal."},{s:"PANTALLA",t:"ESTADO DE SEGURIDAD: SIN INTRUSIÓN DETECTADA. Alertas 24h: Informativas 1,248; Advertencias 37; Críticas 0."},{s:"NARRADOR",t:"Las alertas muestran actividad normal, sin indicios claros de intrusión."},{s:"PANTALLA",t:"REGISTROS DE SEGURIDAD: accesos con credenciales válidas; sin malware conocido; sin explotación de vulnerabilidades; sin actividad de exfiltración; sin modificaciones en sistemas; patrón de tráfico dentro de lo normal."},{s:"HANA",t:"No hay credenciales robadas. No hay malware conocido."},{s:"NARRADOR",t:"Un analista del equipo interpreta los resultados."},{s:"ANALISTA",t:"Entonces no es seguridad."},{s:"HANA",t:"Eso no significa que sea seguro."},{s:"NARRADOR",t:"Hana detecta un patrón inusual en solicitudes legítimas."},{s:"PANTALLA",t:"ANÁLISIS DE SECUENCIA DE SOLICITUDES. 02:16:58 Autenticación válida; 02:17:01 Consulta de datos válida; 02:17:03 Acceso a API válida; 02:17:05 Transferencia interna válida; 02:17:08 Consulta de otro servicio válida; 02:17:11 Acceso a base de datos válida; 02:17:13 Solicitud de configuración válida."},{s:"PANTALLA",t:"FLUJO DE SOLICITUDES: una secuencia detectada atraviesa varios servicios siguiendo caminos permitidos."},{s:"HANA",t:"Alguien -o algo- está usando caminos permitidos de una forma que no esperábamos."},{s:"NARRADOR",t:"Todas las solicitudes son legítimas, pero siguen un patrón anómalo entre múltiples servicios."},{s:"PANTALLA",t:"PATRÓN DETECTADO: secuencia inusual de servicios."},{s:"HANA",t:"No es un ataque directo. Es el uso legítimo de servicios en una secuencia inusual... y muy coordinada."},{s:"NARRADOR",t:"Algo está operando dentro de las reglas, pero con un objetivo que aún no entendemos."},{s:"NARRADOR",t:"Esto es solo una parte del panorama. Necesitamos seguir investigando."},{s:"CIERRE",t:"CONTINÚA... PÁGINA 12."}],
[{s:"TÍTULO",t:"PÁGINA 12 — CUANDO LAS PIEZAS ENCAJAN."},{s:"NARRADOR",t:"Hana analiza las firmas de las solicitudes para identificar comportamientos anómalos."},{s:"PANTALLA",t:"ANÁLISIS DE FIRMAS DE SOLICITUDES. Transporte, Educación, Salud, Finanzas, Comunicaciones y Energía: firma válida, autenticada."},{s:"HANA",t:"Las solicitudes están autenticadas."},{s:"NARRADOR",t:"El mismo patrón aparece en múltiples países y desde sistemas diferentes."},{s:"PANTALLA",t:"ORIGEN DE LAS SOLICITUDES: múltiples regiones conectadas globalmente."},{s:"PANTALLA",t:"DETALLE DE ACCESOS: Norteamérica 12 válido; Sudamérica 9 válido; Europa 14 válido; Asia 11 válido; África 8 válido; Oceanía 6 válido."},{s:"HANA",t:"Y vienen de sistemas diferentes."},{s:"NARRADOR",t:"El análisis revela un patrón complejo que involucra múltiples arquitecturas."},{s:"PANTALLA",t:"ARQUITECTURAS INVOLUCRADAS: Nube pública (AWS), Bases de datos (Oracle), Sistemas legacy (Mainframe), Contenedores (Kubernetes), APIs internas (Microservicios)."},{s:"HANA",t:"Si fuera un atacante, tendría que conocer demasiadas arquitecturas."},{s:"NARRADOR",t:"De repente, aparece una nueva alerta."},{s:"PANTALLA",t:"INCIDENTE DE DISPONIBILIDAD — NODO 7. Hora UTC: 02:23:17. Región: Europa. Servicio: Comunicaciones. Estado: Degradación severa."},{s:"PANTALLA",t:"ESTADO GLOBAL: Servicios 24/32. Incidentes 8. Usuarios afectados 2.3 M."},{s:"HANA",t:"Ahora sí tenemos un problema."},{s:"NARRADOR",t:"Las piezas encajan. No es un incidente aislado. Es un patrón coordinado que afecta múltiples servicios en todo el mundo."},{s:"PANTALLA",t:"UN MISMO MUNDO. MÚLTIPLES CONEXIONES. UNA SOLA VERDAD."},{s:"NARRADOR",t:"El ataque sigue en curso. Pero ahora entendemos mejor cómo funciona. Y estamos un paso más cerca de detenerlo."},{s:"CIERRE",t:"TECH GUARDIANS — EL CÓDIGO DEL MUNDO. CAPÍTULO 1: EL DÍA QUE EL MUNDO SE DETUVO. La investigación continúa..."}],
[{s:"TÍTULO",t:"PÁGINA 13 — CUANDO “ARRIBA” NO SIGNIFICA DISPONIBLE."},{s:"NARRADOR",t:"Noah revisa las alertas en el centro cloud/DevOps para entender por qué los usuarios no pueden acceder, aunque los servicios parecen estar en línea."},{s:"PANTALLA",t:"NEXUS - INFRAESTRUCTURA GLOBAL. Alertas: alta latencia API Movilidad; error 503 Servicios Educación; timeouts Servicios Salud; fallos de conexión Finanzas; latencia elevada Comunicaciones; errores intermitentes Energía."},{s:"PANTALLA",t:"ESTADO DE INFRAESTRUCTURA. CPU global 32%, memoria 46%, red normal: estable. Estado de servicios: Movilidad, Educación, Salud, Finanzas, Comunicaciones y Energía — En línea."},{s:"NOAH",t:"Capacidad suficiente. Red estable. Servicios arriba."},{s:"MAYA",t:"¿Entonces por qué los usuarios no pueden entrar?"},{s:"NOAH",t:"Porque “arriba” no significa disponible."},{s:"PANTALLA",t:"DESDE EL PUNTO DE VISTA DEL USUARIO: Usuario → NEXUS API Gateway → Servicios → Error Tiempo de espera. SISTEMAS EN LÍNEA PERO SIN RESPUESTA PARA EL USUARIO."},{s:"NARRADOR",t:"Noah inicia un análisis de trazas distribuidas para seguir el recorrido de la solicitud a través de todos los servicios conectados a NEXUS."},{s:"NOAH",t:"Sigamos la solicitud de principio a fin."},{s:"PANTALLA",t:"TRAZA DISTRIBUIDA — ID: 7f3a9c2e4b1d. Cliente móvil → API Gateway NEXUS 12 ms → Servicio de Autenticación 28 ms → Servicio de Usuarios 41 ms → Servicio de Perfil 2,340 ms → Servicio de Datos: Timeout. CUELLO DE BOTELLA DETECTADO."},{s:"NOAH",t:"Aquí está... Las solicitudes llegan, pero se quedan esperando en el servicio de perfil."},{s:"PANTALLA",t:"DEPENDENCIAS DEL SERVICIO DE PERFIL: base de datos de perfil, caché distribuida, almacenamiento de objetos, servicio de recomendaciones, servicio de analítica y servicio de notificaciones."},{s:"NOAH",t:"Este componente depende de múltiples servicios en cadena. Necesitamos revisar qué está causando este comportamiento."},{s:"NARRADOR",t:"Lo que parece un solo servicio puede involucrar muchos sistemas. Un problema en uno de ellos puede afectar a millones de personas."},{s:"CIERRE",t:"La investigación continúa..."}],
[{s:"TÍTULO",t:"PÁGINA 14 — CUANDO “ARRIBA” NO SIGNIFICA DISPONIBLE."},{s:"NARRADOR",t:"Noah analiza una traza completa de una solicitud que cruza múltiples servicios conectados a NEXUS."},{s:"PANTALLA",t:"TRAZA DE SOLICITUD - NEXUS. Cliente (App móvil) 12 ms → API Gateway 28 ms → Servicio de Autenticación 35 ms → Servicio de Usuarios 41 ms → Base de datos 62 ms → Servicio Externo 2,340 ms → Respuesta a usuario: Timeout. FALLO EN LA RESPUESTA."},{s:"NOAH",t:"Gateway correcto. Autenticación correcta. Base de datos correcta."},{s:"NOAH",t:"El problema ocurre después, en una dependencia externa."},{s:"PANTALLA",t:"DETALLE DEL COMPONENTE EXTERNO. Servicio: Proveedor de mapas (API). Latencia: 4.00 s. Estado del servicio: disponibilidad operativo; CPU 24%; memoria 37%; red normal."},{s:"NARRADOR",t:"Una dependencia externa responde con un retraso exacto de cuatro segundos."},{s:"NOAH",t:"Otra vez cuatro segundos."},{s:"PANTALLA",t:"HISTORIAL DE INCIDENTES: 02:14:21 Norteamérica Mapas API 4.00 s; 02:15:03 Europa Pago API 4.00 s; 02:16:17 Asia Notificaciones API 4.00 s; 02:17:42 Sudamérica Identidad API 4.00 s; 02:18:35 Oceanía Mapas API 4.00 s."},{s:"NARRADOR",t:"El mismo patrón se repite en diferentes regiones y servicios externos, incluso con proveedores distintos."},{s:"NOAH",t:"Y ocurre en regiones que no comparten proveedor."},{s:"PANTALLA",t:"PROVEEDORES AFECTADOS: GlobalMaps — Norteamérica / Europa; PayLink — Asia / Oceanía; NotifyHub — Sudamérica; IDConnect — múltiples regiones."},{s:"PANTALLA",t:"INCIDENTES EN TIEMPO REAL: Norteamérica Mapas API 4.00 s; Europa Pago API 4.00 s; Asia Notificaciones API 4.00 s; Sudamérica Identidad API 4.00 s; África Análisis API 4.00 s; Oceanía Mapas API 4.00 s."},{s:"NOAH",t:"Esto no es una caída. Es una cadena."},{s:"NARRADOR",t:"Todos los incidentes tienen la misma duración y un patrón común."},{s:"NARRADOR",t:"Noah marca el patrón en el sistema de análisis para que el equipo lo investigue en profundidad."},{s:"PANTALLA",t:"PATRÓN DETECTADO - CADENA DE DEPENDENCIAS. Servicios internos (NEXUS) → múltiples servicios externos → retraso fijo 4.00 s → fallo en la respuesta. Características: múltiples regiones, diferentes proveedores, misma duración (4.00 s), servicios no relacionados, solicitudes legítimas, evento coordinado."},{s:"NOAH",t:"No es un error de un solo servicio. Alguien está usando la infraestructura global de una manera coordinada."},{s:"NOAH",t:"Esto ya no parece una coincidencia."},{s:"NOAH",t:"Alguien conoce muy bien cómo funciona NEXUS..."},{s:"NOAH",t:"Y está usando eso en nuestra contra."},{s:"NARRADOR",t:"Cada respuesta los acerca más a la verdad."},{s:"NARRADOR",t:"El ataque sigue en marcha, pero ahora sabemos que es más grande de lo que imaginamos."},{s:"CIERRE",t:"La investigación continúa... Y apenas comienza."},{s:"CIERRE",t:"CAPÍTULO 2 — NUEVAS AMENAZAS."}],
[{s:"TÍTULO",t:"PÁGINA 15 — LABORATORIO UX/ACCESIBILIDAD: LA OTRA CARA DEL PROBLEMA."},{s:"ESCENA",t:"Sofía prueba la interfaz con un lector de pantalla para evaluar la accesibilidad real del sistema."},{s:"RÓTULO",t:"SOFIA — UX y accesibilidad."},{s:"PANTALLA",t:"INTERFAZ VISUAL: Servicio disponible. Continuar."},{s:"LECTOR DE PANTALLA",t:"Error. Estado desconocido. Botón: Continuar. Estado: no disponible. Elemento sin etiqueta válida. La aplicación no responde."},{s:"SOFIA",t:"La interfaz y el sistema no están contando la misma historia."},{s:"ESCENA",t:"Un usuario mayor intenta realizar un trámite en un kiosco de autoservicio."},{s:"USUARIO",t:"¿Puedo continuar o no?"},{s:"SOFIA",t:"Ese es el problema. El sistema obliga al usuario a adivinar."},{s:"ESCENA",t:"El equipo analiza barreras de accesibilidad detectadas en distintos servicios."},{s:"PANTALLA",t:"BARRERAS ENCONTRADAS: Etiquetas incompletas 142. Contraste insuficiente 87. Elementos sin nombre 64. Navegación no secuencial 53. Mensajes poco claros 48."},{s:"PANTALLA",t:"EJEMPLO DE PROBLEMA. Vista visual: Correo electrónico, usuario@ejemplo.com, Enviar. Lector de pantalla: Campo de edición sin nombre. Estado desconocido."},{s:"PANTALLA",t:"IMPACTO EN USUARIOS: Personas mayores, dificultad para entender y completar trámites. Personas con discapacidad, información inaccesible o incompleta. Usuarios de diferentes regiones, experiencias inconsistentes según idioma y dispositivo."},{s:"SOFIA",t:"La accesibilidad no es un extra. Es parte de la seguridad, la continuidad del servicio y la confianza de los usuarios."},{s:"SOFIA",t:"Si una persona no puede usarlo, el sistema no funciona de verdad."},{s:"PANTALLA",t:"BUENAS PRÁCTICAS: Interfaces compatibles con lectores de pantalla. Etiquetas y roles semánticos correctos. Contraste y legibilidad adecuados. Navegación por teclado. Mensajes claros y consistentes. Pruebas con usuarios reales de diferentes perfiles."},{s:"NARRADOR",t:"Un sistema inclusivo es más resiliente y permite que más personas se mantengan conectadas, incluso en situaciones críticas."},{s:"ESCENA",t:"El equipo integra la accesibilidad en la estrategia del próximo fase."},{s:"NARRADOR",t:"Un mundo más seguro también es un mundo más inclusivo."},{s:"NARRADOR",t:"La tecnología debe estar al servicio de todas las personas."}],
[{s:"TÍTULO",t:"PÁGINA 16 — SOFÍA CONFIRMA EL IMPACTO REAL."},{s:"ESCENA",t:"Sofía documenta el impacto en usuarios reales durante las pruebas de accesibilidad."},{s:"RÓTULO",t:"SOFIA — UX y accesibilidad."},{s:"PANTALLA",t:"PRUEBA DE ACCESIBILIDAD. Interfaz visual: Servicio disponible, Continuar. Lector de pantalla: Error. Estado desconocido."},{s:"PANTALLA",t:"DETALLES DE LA PRUEBA. Usuario: u_7842. Servicio: Pago en línea. Dispositivo: Lector de pantalla. Resultado: No puede completar la tarea."},{s:"SOFIA",t:"No es solo un mensaje incorrecto. Puede impedir que una persona complete una tarea crítica."},{s:"PANTALLA",t:"IMPACTO EN EL USUARIO: No puede completar el pago de un servicio esencial. Debe buscar ayuda o abandonar el proceso."},{s:"ESCENA",t:"Otro dispositivo muestra información diferente para el mismo usuario y servicio."},{s:"SOFIA",t:"Mismo usuario. Mismo servicio. Dos respuestas."},{s:"PANTALLA",t:"DISPOSITIVO A — App móvil: Pago exitoso. Estado: Completado. Tiempo: 12 s. Referencia: #4582A."},{s:"PANTALLA",t:"DISPOSITIVO B — Navegador + lector de pantalla: Error en el servicio. Estado: Desconocido. Tiempo: 4 s. Código: E-503. Intentar nuevamente."},{s:"ESCENA",t:"Pocos minutos después, Sofía recibe una notificación masiva de incidentes."},{s:"PANTALLA",t:"INCIDENTES SIMULTÁNEOS DETECTADOS: Pago en línea 245 incidentes. Inicio de sesión 189. Consulta de datos 173. Servicios educativos 142. Servicios de salud 138."},{s:"ESCENA",t:"Sofía observa la información desde la sala principal de monitoreo."},{s:"SOFIA",t:"Esto ya no es un problema de interfaz. Tiene un impacto real en millones de personas."},{s:"PANTALLA",t:"USUARIOS AFECTADOS (ESTIMADO): 2.3 M. Regiones afectadas 42. Servicios involucrados 24. Incidentes reportados 1,248. Tendencia +320%."},{s:"ESCENA",t:"Sofía comparte sus hallazgos con el equipo."},{s:"SOFIA",t:"Esto confirma que el ataque afecta a personas reales en diferentes servicios y regiones."},{s:"SOFIA",t:"La tecnología debe estar al servicio de las personas, especialmente en momentos críticos."},{s:"NARRADOR",t:"La investigación apenas comienza. Ahora entendemos la magnitud del problema y la importancia de nuestra misión."}],
[{s:"TÍTULO",t:"PÁGINA 17 — EL EQUIPO ACTÚA."},{s:"ESCENA",t:"De repente, todos reciben la misma alerta en sus sistemas. El ataque se está expandiendo a nivel global."},{s:"SISTEMA",t:"PRIORIDAD 1 — MÚLTIPLES SERVICIOS AFECTADOS."},{s:"PANTALLA",t:"Transporte. Salud. Educación. Finanzas. Comunicaciones. Energía. Servicios en la nube. Servicios gubernamentales."},{s:"PANTALLA",t:"INCIDENTES EN TIEMPO REAL: 3,248. SERVICIOS AFECTADOS: 126 países."},{s:"AKIRA",t:"Necesito los logs centrales."},{s:"MAYA",t:"Necesito reproducirlo."},{s:"LEO",t:"Necesito más datos."},{s:"HANA",t:"Primero, no empeoremos el incidente."},{s:"PANTALLA",t:"ACCIÓN AUTOMÁTICA — Despliegue masivo en la red — BLOQUEADA."},{s:"NOAH",t:"Voy a revisar la infraestructura en la nube."},{s:"SOFIA",t:"Voy a evaluar el impacto en los usuarios y documentarlo en tiempo real."},{s:"PANTALLA",t:"ESTADO GLOBAL DE SERVICIOS: Transporte, Salud, Educación, Finanzas, Comunicaciones, Energía, Nube y datos, Servicios gubernamentales. 3,248 incidentes. 126 países. 24.8 M usuarios afectados. 8 h 17 m de duración en curso."},{s:"PANTALLA",t:"COLABORACIÓN EN TIEMPO REAL — NEXUS: Análisis de datos. Monitoreo global. Bloqueo de amenazas. Evaluación de impacto. Coordinación del equipo. Respuesta en tiempo real."},{s:"NARRADOR",t:"Esto es más grande de lo que imaginábamos. Pero no estamos solos. Somos un equipo."},{s:"EQUIPO",t:"Cada uno aporta su experiencia. Juntos podemos enfrentar esto."},{s:"EQUIPO",t:"El mundo depende de lo que hagamos ahora. Debemos mantenernos coordinados y seguir adelante."},{s:"CIERRE",t:"UN ATAQUE GLOBAL. SEIS PERSONAS. UN MISMO PROPÓSITO."},{s:"CIERRE",t:"LA INFORMACIÓN NOS CONECTA. EL EQUIPO NOS HACE FUERTES."}],
[{s:"TÍTULO",t:"PÁGINA 18 — EL MUNDO LO NOTA."},{s:"NARRADOR",t:"A las 09:42, las anomalías dejaron de ser pequeñas."},{s:"NARRADOR",t:"Las personas comenzaron a notar los problemas en su vida diaria."},{s:"ESCENA",t:"Una estación ferroviaria se llena de personas mientras los paneles cambian horarios."},{s:"PANTALLA",t:"ESTACIÓN CENTRAL. Madrid: Cancelado 09:40. Barcelona: Retrasado 09:42. Valencia: Retrasado 09:45. Sevilla: Cancelado 09:50. Málaga: En revisión 09:55."},{s:"PANTALLA",t:"SERVICIOS INTERRUMPIDOS — Fallo en sistemas de señalización."},{s:"NARRADOR",t:"El transporte se ve afectado en múltiples ciudades. Miles de personas enfrentan retrasos y cancelaciones."},{s:"ESCENA",t:"Los hospitales activan procedimientos de contingencia ante la falta de acceso a sus sistemas."},{s:"PANTALLA",t:"HOSPITAL GENERAL — MODO CONTINGENCIA. Sistemas de pacientes: Fuera de línea. Historial médico: No disponible. Laboratorio: Operativo limitado. Imágenes médicas: En respaldo. Admisión: Manual."},{s:"NARRADOR",t:"Se trabaja con procesos manuales para garantizar la atención. La seguridad de los pacientes es la prioridad."},{s:"ESCENA",t:"Una universidad pierde temporalmente la autenticación."},{s:"PANTALLA",t:"UNIVERSIDAD NACIONAL — AUTENTICACIÓN NO DISPONIBLE. No es posible acceder a los servicios en este momento. Intente más tarde."},{s:"PANTALLA",t:"SERVICIOS AFECTADOS: Aula virtual. Correo institucional. Biblioteca digital. Inscripción de materias. Plataforma de investigación."},{s:"NARRADOR",t:"Estudiantes y profesores no pueden acceder a sus cuentas. Las actividades académicas se ven interrumpidas en múltiples campus."},{s:"ESCENA",t:"Una empresa logística detiene sus rutas automatizadas ante fallos en los sistemas de control."},{s:"PANTALLA",t:"CENTRO LOGÍSTICO GLOBAL — RUTAS AUTOMATIZADAS DETENIDAS. Gestión de flota: Error. Seguimiento GPS: Sin datos. Control de almacén: Fuera de línea. Planificación de rutas: Suspendida. Sistemas de aduanas: Restringido."},{s:"NARRADOR",t:"Mercancías detenidas, rutas canceladas y operaciones en modo manual. El impacto afecta la cadena de suministro global."},{s:"PANTALLA",t:"IMPACTO GLOBAL EN TIEMPO REAL: 126 países afectados. 24 servicios críticos. 2.3 M usuarios afectados."},{s:"NARRADOR",t:"Y por primera vez, el mundo comenzó a notarlas. Lo que inició en las sombras de NEXUS ahora afecta a millones de personas."},{s:"NARRADOR",t:"Esto ya no es un problema técnico aislado. Es una crisis global. Y apenas estamos viendo el comienzo."},{s:"EQUIPO",t:"Diferentes lugares. Un mismo momento. Un mismo efecto."},{s:"EQUIPO",t:"El mundo está conectado. Y también sus riesgos."},{s:"ORION",t:"Nuestra misión es más importante que nunca."},{s:"CIERRE",t:"UN PROBLEMA EN UN LUGAR PUEDE DETENER UN MUNDO ENTERO."},{s:"CIERRE",t:"DISTINTAS REALIDADES. UN MISMO ORIGEN."}],
[{s:"TÍTULO",t:"PÁGINA 19 — UN DESAFÍO MÁS GRANDE DE LO QUE PARECÍA."},{s:"ESCENA",t:"En un centro internacional de coordinación, equipos de diferentes países analizan el incidente en tiempo real."},{s:"PANTALLA",t:"CENTRO GLOBAL DE COORDINACIÓN — INCIDENTE NEXUS — VISTA MUNDIAL. Incidentes activos: 3,248."},{s:"PANTALLA",t:"Transporte 842. Salud 621. Educación 496. Finanzas 378. Comunicaciones 342. Energía 310. Gobierno 259. Otros."},{s:"OPERADOR 1",t:"¿Ataque coordinado?"},{s:"OPERADOR 2",t:"No vemos una firma común."},{s:"OPERADOR 3",t:"¿Actualización defectuosa?"},{s:"OPERADOR 4",t:"Los sistemas afectados no comparten versión."},{s:"DIRECTORA",t:"Entonces dejen de buscar una única aplicación."},{s:"DIRECTORA",t:"Busquen una dependencia."},{s:"DIRECTORA",t:"Esto parece ser un ataque que se propaga a través de conexiones entre servicios e infraestructuras. La clave está en cómo están interconectados."},{s:"PANTALLA",t:"SERVICIOS AFECTADOS EN TIEMPO REAL: 3,248 incidentes. 126 países. 2.3 M usuarios afectados. Principales regiones: Asia 28%, América del Norte 24%, Europa 22%, América del Sur 14%, África 8%, Oceanía 4%."},{s:"NARRADOR",t:"Es más complejo de lo que imaginábamos."},{s:"NARRADOR",t:"No se trata de un solo sistema ni de un solo país. Es un mundo interconectado."},{s:"EQUIPO",t:"Entender las dependencias será clave para detenerlo."},{s:"EQUIPO",t:"Necesitamos combinar nuestros conocimientos."},{s:"EQUIPO",t:"Esto apenas comienza."},{s:"NARRADOR",t:"El mundo enfrenta un desafío sin precedentes. Pero también una oportunidad: trabajar juntos como nunca antes."},{s:"NARRADOR",t:"Diferentes países. Diferentes personas. Un mismo propósito."},{s:"CIERRE",t:"Las conexiones que nos unen también pueden protegernos."}],
[{s:"TÍTULO",t:"PÁGINA 20 — LAS PIEZAS EN SU LUGAR."},{s:"NARRADOR",t:"El equipo profundiza en los datos. Cada uno analiza una parte del rompecabezas. A medida que comparten sus hallazgos, un patrón comienza a emerger."},{s:"PANTALLA",t:"FALLOS SIMULTÁNEOS. MÚLTIPLES SERVICIOS. DIFERENTES REGIONES. PATRÓN TEMPORAL COMÚN. EN INVESTIGACIÓN."},{s:"PANTALLA",t:"FLUJO DE ANÁLISIS: Recopilación de datos. Correlación de eventos. Análisis de patrones. Validación cruzada. Conclusiones."},{s:"AKIRA",t:"Las aplicaciones son distintas, los servicios están en diferentes países y usan tecnologías diferentes..."},{s:"PANTALLA",t:"REPOSITORIO DE TRAZAS GLOBALES: Servicio de pagos 2.4M logs; Plataforma educativa 1.8M logs; Sistema de salud 3.1M logs; Red de transporte 2.0M logs; Portal gubernamental 1.6M logs; Servicio en la nube 2.8M logs."},{s:"MAYA",t:"...pero los fallos aparecen en ventanas idénticas."},{s:"PANTALLA",t:"COMPARACIÓN DE LÍNEA DE TIEMPO: Pago en línea, Educación, Salud, Transporte, Gobierno y Nube muestran fallos concentrados en las mismas ventanas."},{s:"LEO",t:"Probabilidad de coincidencia: demasiado baja. Esto no es aleatorio. Hay un patrón sistémico."},{s:"PANTALLA",t:"ANÁLISIS DE CORRELACIÓN: Pago en línea 0.91; Educación 0.87; Salud 0.89; Transporte 0.86; Gobierno 0.88; Nube 0.90. Probabilidad de coincidencia aleatoria < 0.0001%. Patrón estadísticamente significativo."},{s:"HANA",t:"Y no hay una intrusión tradicional. No vemos movimientos laterales, exfiltración de datos o explotación de vulnerabilidades conocidas."},{s:"PANTALLA",t:"RUTAS DE ACCESO ANALIZADAS: Acceso externo sin actividad; movimiento lateral no detectado; ejecución de código malicioso no detectado; exfiltración de datos no detectado; escalada de privilegios no detectado; persistencia no detectado."},{s:"NARRADOR",t:"El mismo patrón se repite en múltiples regiones y servicios. Todo apunta a una dependencia común."},{s:"AKIRA",t:"No es un ataque convencional. Es algo más profundo. Una conexión que todos comparten."},{s:"EQUIPO",t:"Estamos encontrando la pieza que faltaba. Ahora sabemos por dónde seguir investigando."},{s:"EQUIPO",t:"Si entendemos esta dependencia, podremos anticiparnos, proteger a más personas y evitar que se repita."},{s:"CIERRE",t:"Las pistas se conectan. El equipo avanza. El mundo sigue en riesgo, pero ahora tienen una dirección."},{s:"CIERRE",t:"Con más información, más colaboración y un propósito más fuerte."}],
[{s:"TÍTULO",t:"PÁGINA 21 — LA PIEZA QUE NOS CONECTA: UN MISMO PUNTO. UN SOLO IMPACTO."},{s:"NOAH",t:"Todos pasan por capas distintas de NEXUS."},{s:"NOAH",t:"Aunque las aplicaciones son diferentes, todas utilizan servicios comunes de la plataforma."},{s:"PANTALLA",t:"ARQUITECTURA DE SERVICIOS GLOBALES: Aplicaciones y servicios de Salud, Transporte, Educación, Finanzas, Gobierno y Comercio convergen mediante APIs y servicios intermedios en NEXUS y la infraestructura global."},{s:"SOFIA",t:"Entonces no importa qué aplicación use la persona."},{s:"SOFIA",t:"Si la capa compartida falla, el usuario paga la consecuencia. El impacto no se queda en un solo sector. Afecta a todos."},{s:"AKIRA",t:"Veo el mismo patrón en los registros de diferentes aplicaciones. Todo apunta a un punto común."},{s:"MAYA",t:"Las fallas ocurren en la misma secuencia y en las mismas ventanas de tiempo. Es consistente en todos los servicios."},{s:"LEO",t:"La correlación entre sistemas es muy alta. La probabilidad de que sea una coincidencia es prácticamente nula."},{s:"HANA",t:"No hay señales de una intrusión tradicional. Parece un fallo en la capa compartida, no un ataque a una sola aplicación."},{s:"ORION",t:"Todos los indicadores convergen en NEXUS. Es el punto de conexión entre servicios, personas y países."},{s:"NARRADOR",t:"Seis especialistas. Seis lugares. La misma pregunta."},{s:"PANTALLA",t:"Un mismo punto. Un impacto global. Diferentes aplicaciones. Múltiples sectores. Mismos tiempos de falla. Un servicio compartido. Impacto en todo el mundo."},{s:"AKIRA",t:"Lo que estamos viendo es más grande que un ataque. Es una oportunidad para entender cómo el mundo está conectado y cómo la tecnología puede servir a las personas cuando se diseña con propósito."},{s:"EQUIPO",t:"La respuesta no está en una sola disciplina. Está en la unión de nuestras habilidades, nuestras perspectivas y nuestra convicción de construir un mundo mejor."},{s:"EQUIPO",t:"La tecnología es poderosa, pero su verdadero valor está en las personas que la usan, en las que la crean y en las que se protegen unas a otras."},{s:"CIERRE",t:"Diferentes caminos. Un mismo propósito."},{s:"CIERRE",t:"UN MUNDO INTERCONECTADO. MÁS PERSONAS. MÁS PERSPECTIVAS. MAYOR IMPACTO."},{s:"CIERRE",t:"EL CAMBIO TAMBIÉN DEPENDE DE NOSOTROS. Y JUNTOS PODEMOS CONSTRUIR UN FUTURO MEJOR."}],
[{s:"TÍTULO",t:"PÁGINA 22 — UN MUNDO INTERCONECTADO. UN MISMO MISTERIO."},{s:"NARRADOR",t:"¿Qué puede fallar al mismo tiempo en sistemas que nunca fueron diseñados para fallar juntos?"},{s:"NARRADOR",t:"La tecnología conecta un mundo extraordinario. Pero también crea dependencias que no siempre vemos."},{s:"PANTALLA",t:"NEXUS — ESTADO GLOBAL: DEGRADADO."},{s:"PANTALLA",t:"SERVICIOS AFECTADOS: Transporte, Salud, Educación, Finanzas, Comunicaciones, Energía, Gobierno, Comercio, Servicios en la nube y otros."},{s:"ESCENA",t:"Una enorme red luminosa envuelve el planeta. Zonas rojas aparecen en lugares muy separados: Nueva York, Londres, São Paulo, Ciudad de México, Madrid, El Cairo, Tokio, Sídney, Nairobi y Bangkok."},{s:"NARRADOR",t:"Un mismo mundo. Múltiples servicios. Millones de personas. Una única red que los conecta."},{s:"NARRADOR",t:"Lo que está ocurriendo en un lugar, puede afectarnos a todos. Y esto es solo el comienzo de una historia mucho más grande."},{s:"CIERRE",t:"Un mundo más conectado. Un mismo destino."}],
[{s:"TÍTULO",t:"PÁGINA 23 — DECISIONES EN TIEMPO REAL: EL PESO DE CADA ACCIÓN."},{s:"NARRADOR",t:"El equipo se reúne con el centro de coordinación para analizar la siguiente decisión. Cada acción puede tener un impacto global. No hay margen para errores."},{s:"DIRECTORA",t:"Aíslen el segmento 14."},{s:"PANTALLA",t:"INFRAESTRUCTURA GLOBAL — NEXUS. Segmento 11 estable; 12 estable; 13 advertencia; 14 en análisis; 15 estable; 16 advertencia; 17 estable."},{s:"PANTALLA",t:"SERVICIOS VINCULADOS: Salud 3 servicios; Transporte 2; Finanzas 1; Educación 2; Gobierno 1; Comunicaciones 2."},{s:"NOAH",t:"Si lo aislamos ahora, tres servicios de salud perderán redundancia."},{s:"NOAH",t:"Podría afectar hospitales en diferentes países y aumentar el riesgo para miles de personas."},{s:"PANTALLA",t:"SERVICIOS DE SALUD AFECTADOS: Hospital Central - Madrid; Red Hospitalaria - São Paulo; Sistema de Clínicas - Tokio. PÉRDIDA DE REDUNDANCIA: 3 SERVICIOS CRÍTICOS."},{s:"HANA",t:"Y no sabemos si el segmento es causa o víctima."},{s:"PANTALLA",t:"ANÁLISIS DE SEGMENTO 14: Tráfico anómalo sí; intrusión confirmada no; origen del incidente desconocido; posible propagación sí; relación con otros nodos en análisis."},{s:"MAYA",t:"Los datos muestran fallos en servicios que dependen de este segmento, pero también en otros que no."},{s:"MAYA",t:"Necesitamos más información para entender el impacto real."},{s:"LEO",t:"La correlación indica que este segmento está involucrado, pero no confirma que sea el origen."},{s:"LEO",t:"Necesitamos más datos para reducir la incertidumbre."},{s:"SOFIA",t:"Cualquier interrupción afectará a personas reales. Debemos considerar el impacto en la vida diaria, especialmente en servicios críticos como la salud."},{s:"AKIRA",t:"Aislar un segmento tan grande puede generar efectos en cadena. Debemos simular los escenarios antes de tomar una decisión."},{s:"DIRECTORA",t:"Entonces necesitamos evidencia antes de tocarlo."},{s:"DIRECTORA",t:"No podemos aislarlo solo por precaución. Cada decisión debe estar basada en datos y en el impacto para las personas."},{s:"ORION",t:"Estoy analizando más datos en tiempo real y ejecutando simulaciones de impacto. Les informaré en cuanto tenga resultados más precisos."},{s:"NARRADOR",t:"Cada decisión importa. No se trata solo de tecnología, sino de personas, de servicios y de un mundo que depende de conexiones que muchos ni siquiera ven."},{s:"NARRADOR",t:"El mundo está más conectado de lo que imaginamos. Un problema en un punto puede afectar a millones de personas en lugares muy distintos."},{s:"CIERRE",t:"MÁS CONOCIMIENTO. MEJORES DECISIONES. UN MUNDO MÁS SEGURO."},{s:"CIERRE",t:"EL CAMBIO TAMBIÉN DEPENDE DE NOSOTROS. PREPARADOS PARA LO QUE VIENE."}],
[{s:"TÍTULO",t:"PÁGINA 24: LA PISTA DETRÁS DE LAS ANOMALÍAS."},{s:"ESCENA",t:"Maya revisa timestamps de sus pruebas."},{s:"MAYA",t:"Esperen."},{s:"MAYA",t:"Estoy revisando los timestamps de las pruebas y hay un patrón que se repite."},{s:"PANTALLA",t:"Ejecución de pruebas: 10:42:16 OK, Login exitoso. 10:42:17 ERROR, Error 500 - Token inválido. 10:45:03 OK, Consulta de datos. 10:45:04 ERROR, Error 500 - Servicio caído. 10:48:21 OK, Actualización completada. 10:48:22 ERROR, Error 503 - Time out. 10:51:10 OK, Cierre de sesión. 10:51:11 ERROR, Error 500 - Sesión inválida."},{s:"ESCENA",t:"Maya amplía cuatro eventos."},{s:"PANTALLA",t:"Evento 1 - Login. 10:42:16 Respuesta válida: Login exitoso, código 200. 10:42:17 Anomalía: Error 500, Token inválido."},{s:"PANTALLA",t:"Evento 2 - Consulta. 10:45:03 Respuesta válida: Datos obtenidos, código 200. 10:45:04 Anomalía: Error 500, Servicio caído."},{s:"PANTALLA",t:"Evento 3 - Actualización. 10:48:21 Respuesta válida: Registro actualizado, código 200. 10:48:22 Anomalía: Error 503, Time out."},{s:"PANTALLA",t:"Evento 4 - Cierre de sesión. 10:51:10 Respuesta válida: Cierre completado, código 200. 10:51:11 Anomalía: Error 500, Sesión inválida."},{s:"MAYA",t:"Cada anomalía comienza exactamente después de una respuesta válida."},{s:"MAYA",t:"No parece ser un error aleatorio. Es un patrón claro en todas las pruebas."},{s:"PANTALLA",t:"Respuesta válida → 1 segundo después → Anomalía."},{s:"ESCENA",t:"Akira mira el código."},{s:"AKIRA",t:"Eso no tiene sentido. Una respuesta válida debería cerrar el flujo."},{s:"AKIRA",t:"Si el sistema devuelve un resultado correcto, no debería generar un error inmediatamente después."},{s:"MAYA",t:"¿Y si alguien está usando el resultado correcto para provocar el siguiente error?"},{s:"MAYA",t:"Podría ser parte de un ataque donde primero se ejecuta una operación válida para activar algo en segundo plano y luego generar la falla."},{s:"PANTALLA",t:"PATRÓN DETECTADO: Respuesta válida seguida de anomalía (1 segundo)."},{s:"AKIRA",t:"Esto no es solo un error... Alguien conoce cómo funciona el sistema y lo está utilizando en nuestra contra."}],
[{s:"TÍTULO",t:"PÁGINA 25 — UN PATRÓN QUE NOS OBSERVA."},{s:"ESCENA",t:"Leo analiza las secuencias de eventos en múltiples servicios y regiones."},{s:"LEO",t:"No son fallos aleatorios. Hay orden."},{s:"LEO",t:"Cada incidente sigue una secuencia similar en diferentes servicios, países y horarios."},{s:"PANTALLA",t:"Análisis de secuencias: Pago en línea, Educación, Salud, Transporte, Gobierno, Comercio y Nube muestran el mismo patrón."},{s:"PANTALLA",t:"Respuesta válida → Respuesta válida → Anomalía → Recuperación."},{s:"LEO",t:"Cada incidente parece una prueba. Primero permite el acceso, luego genera la falla y finalmente se recupera."},{s:"HANA",t:"¿Una prueba de qué?"},{s:"LEO",t:"De nosotros."},{s:"HANA",t:"No es un ataque convencional, ni una intrusión tradicional. Parece diseñado para evaluar algo específico."},{s:"LEO",t:"El mismo patrón se ejecuta en distintas regiones, servicios y tipos de usuarios. No afecta solo a la tecnología."},{s:"NARRADOR",t:"Esto implica que alguien nos está observando, analizando nuestras respuestas y aprendiendo de ellas."},{s:"NARRADOR",t:"La falla no es el objetivo. El verdadero objetivo es lo que hacemos después."},{s:"PANTALLA",t:"Objetivo del patrón: observar nuestras respuestas, analizar nuestras decisiones, aprender de nuestro comportamiento y preparar algo más grande."},{s:"NARRADOR",t:"No se trata solo de sistemas. Estamos siendo evaluados."},{s:"NARRADOR",t:"Cada respuesta que damos, cada decisión que tomamos, puede ser parte de algo mucho más grande."}],
[{s:"TÍTULO",t:"PÁGINA 26 — UNA HIPÓTESIS MÁS OSCURA."},{s:"AKIRA",t:"Nadie probaría producción afectando hospitales. Eso no tiene sentido. El impacto en la vida de las personas es demasiado grave."},{s:"HANA",t:"Una persona responsable, no."},{s:"HANA",t:"Pero lo que vemos es demasiado preciso. Alguien conoce muy bien cómo funcionan los sistemas y sus dependencias."},{s:"SOFIA",t:"Pero estamos asumiendo que quien lo hace piensa como nosotros."},{s:"SOFIA",t:"Puede que no le importe el daño a las personas, o que incluso lo considere parte del objetivo."},{s:"LEO",t:"Los patrones muestran conocimiento profundo de la infraestructura, tiempos de respuesta y dependencias críticas."},{s:"LEO",t:"Esto parece diseñado para provocar el máximo impacto posible."},{s:"NOAH",t:"Entonces tenemos que considerar que podría ser un actor que no sigue reglas éticas ni convencionales. Alguien que ve el mundo de una forma diferente."},{s:"ORION",t:"Los datos indican que el atacante tiene un conocimiento avanzado de NEXUS y de sus interconexiones."},{s:"ORION",t:"La precisión de los eventos sugiere planificación y un objetivo mayor que una simple interrupción."},{s:"NOAH",t:"Tenemos una nueva alerta. Otro segmento está mostrando comportamiento inusual."},{s:"SISTEMA",t:"ALERTA DEL SISTEMA. NODO 31 — comportamiento anómalo. Región: Europa. Servicios vinculados: Salud / Transporte. Estado: En análisis."},{s:"SISTEMA",t:"Tiempo estimado para el siguiente evento: 00:00:30."},{s:"NOAH",t:"Tenemos treinta segundos antes del siguiente evento. Esto ya no es solo un análisis. Está sucediendo ahora."},{s:"AKIRA",t:"Si el mismo patrón se repite en otro segmento, ya no podemos descartarlo como una coincidencia. Alguien está ejecutando esto de forma coordinada."},{s:"HANA",t:"Y cada nuevo evento afecta a más personas. Necesitamos entender su objetivo antes de que sea demasiado tarde."},{s:"SOFIA",t:"Puede que no podamos detener el siguiente evento. Pero sí podemos aprender del patrón y prepararnos para lo que viene después."},{s:"LEO",t:"Cada incidente nos da más información. Debemos mantener la calma, seguir analizando y anticipar sus siguientes movimientos."}],
[{s:"TÍTULO",t:"PÁGINA 27 — LA CUENTA REGRESIVA."},{s:"NARRADOR",t:"La cuenta regresiva avanza mientras el equipo se prepara para el siguiente evento del patrón."},{s:"PANTALLA",t:"Tiempo para el siguiente evento: 00:00:15. Secuencia en curso: Login → Consulta de datos → Autenticación en proceso → Respuesta ?"},{s:"AKIRA",t:"Si sigue la secuencia, consultará autenticación."},{s:"AKIRA",t:"El siguiente servicio debería ser el de gestión de identidades. Prepárense."},{s:"PANTALLA",t:"Servicio esperado: Identidad y autenticación (IAM). Endpoint: /api/auth/validate. Método: POST. Importancia: Crítica. Dependencias: 12 servicios."},{s:"MAYA",t:"Registro completo. Sin filtros."},{s:"MAYA",t:"Quiero todas las cabeceras, los tiempos de respuesta y el contenido de los eventos, tal como llegan."},{s:"PANTALLA",t:"Captura de datos: logs completos, sin filtros, cabeceras HTTP, tiempos de respuesta, metadatos y almacenamiento seguro."},{s:"HANA",t:"Nada se bloquea sin mi autorización."},{s:"HANA",t:"Monitoreo todo el tráfico en tiempo real. Si detecto algo fuera del patrón, lo detengo."},{s:"LEO",t:"Analizando el patrón... Diez segundos."},{s:"LEO",t:"La respuesta debería seguir la misma secuencia de comportamiento que en los incidentes anteriores."},{s:"NOAH",t:"El tráfico está llegando. Todo coincide con el patrón."},{s:"NOAH",t:"Si la respuesta no sigue la secuencia, tendremos confirmación del ataque."},{s:"SOFIA",t:"Esto puede afectar a millones de personas en segundos. Mantengámonos enfocados. Estamos a punto de ver la siguiente pieza del patrón."}],
[{s:"TÍTULO",t:"PÁGINA 28 — LA RESPUESTA QUE NO DEBERÍA ESTAR AHÍ."},{s:"NARRADOR",t:"Faltan pocos segundos para la respuesta del sistema. El equipo observa en tiempo real lo que ocurre."},{s:"PANTALLA",t:"Tiempo para la respuesta: 00:00:03. 3... 2... 1."},{s:"PANTALLA",t:"POST /api/auth/validate. Conectando. Enviando solicitud. Respuesta recibida. Tiempo de respuesta: 842 ms."},{s:"AKIRA",t:"No pasó nada."},{s:"AKIRA",t:"La respuesta es correcta y el servicio funciona como se esperaba."},{s:"PANTALLA",t:"Resultado en pantalla: 200 OK. Tiempo: 842 ms. Servicio: /api/auth/validate. Estado: Éxito. Usuario: Autenticación."},{s:"MAYA",t:"Sí pasó."},{s:"MAYA",t:"Hay un cambio muy pequeño, pero no debería estar aquí."},{s:"PANTALLA",t:"Respuesta del sistema: status success; token; user; debug_mode: true; expires_in: 3600. Campo que no debería existir: debug_mode."},{s:"MAYA",t:"Aquí. El sistema respondió correctamente... y añadió esto."},{s:"LEO",t:"Este campo no es parte del diseño de la API. Podría ser una señal de que están ejecutando algo adicional en segundo plano."},{s:"HANA",t:"Podría ser una puerta para activar más funcionalidades. Necesitamos revisar si aparece en otros servicios."},{s:"NOAH",t:"Voy a verificar si este campo se replica en otras regiones y entornos. Si aparece en varios servicios, confirmaría que es parte del patrón."},{s:"SOFIA",t:"Parece un detalle pequeño, pero puede abrir un gran riesgo si se usa para hacer algo sin autorización. Documentemos todo y revisemos el impacto en los usuarios."},{s:"NARRADOR",t:"Esto apenas comienza. Un pequeño campo puede ser la llave a algo mucho más grande."}],
[{s:"TÍTULO",t:"PÁGINA 29 — UN CAMPO QUE NO DEBERÍA EXISTIR."},{s:"NARRADOR",t:"El equipo analiza en detalle el campo que no debería estar en la respuesta."},{s:"AKIRA",t:"Eso no está en el esquema. No debería venir en la respuesta. No está documentado."},{s:"PANTALLA",t:"Campo no documentado: internal_trace_id = a7f3c9e8b1d4f6a2e9c7d3b0e5f1a8c4. Tipo: cadena hexadecimal. Longitud: 32 caracteres. Formato: desconocido. En esquema: no. Documentación: no existe."},{s:"NOAH",t:"Ningún servicio debería generarlo. No corresponde con el comportamiento esperado de la API."},{s:"HANA",t:"¿Puede ejecutarse? ¿Es un script, una instrucción o algún tipo de comando?"},{s:"AKIRA",t:"No. Parece solo datos. No tiene un formato ejecutable directo. Pero podrían estar codificando información en esa cadena."},{s:"LEO",t:"Voy a copiar la cadena para analizarla."},{s:"LEO",t:"O un mensaje. Podría ser un identificador que contiene más información de la que vemos."},{s:"HANA",t:"Aunque no se pueda ejecutar directamente, podría usarse para activar algo en otro servicio. Necesitamos rastrear si este identificador aparece en otras partes del sistema."},{s:"SOFIA",t:"También podría ser información de seguimiento interna que la aplicación no debería mostrar. Hay que revisar el impacto en los usuarios y si esta información expone datos sensibles."},{s:"NOAH",t:"Vamos a buscar esta cadena en los logs de todos los servicios. Si aparece en otros sistemas, confirmaría que es parte de un patrón más grande."},{s:"PANTALLA",t:"Búsqueda en logs globales: encontrado en autenticación, usuarios, salud y educación; no encontrado en pagos ni transporte."},{s:"NARRADOR",t:"Esto confirma que no es un error aislado. Alguien o algo está dejando huellas. Este campo puede ser parte de un mensaje o de una instrucción más grande."}],
[{s:"TÍTULO",t:"PÁGINA 30 — PIEZAS DE UN MENSAJE."},{s:"ESCENA",t:"Leo procesa la cadena usando diferentes métodos de análisis y decodificación."},{s:"LEO",t:"No es cifrado estándar. No produce un texto legible con los métodos comunes que conocemos."},{s:"PANTALLA",t:"Análisis de la cadena: Base64 no válido; Base32 no válido; Hex a texto sin resultado legible; hash común no coincide; compresión no válida; análisis binario: datos no estructurados. Resultado: formato desconocido."},{s:"ESCENA",t:"Maya busca el mismo campo en incidentes anteriores."},{s:"MAYA",t:"Busquen el mismo campo en los incidentes anteriores. Debe existir un patrón."},{s:"PANTALLA",t:"Fragmentos encontrados: Login a7f3c9e8; Consulta b1d4f6a2; Actualización e9c7d3b0; Cierre de sesión e5f1a8c4."},{s:"MAYA",t:"Sí existe. Aparece en varios eventos, pero nunca completo en una sola respuesta."},{s:"NARRADOR",t:"El equipo analiza los resultados y confirma que la cadena aparece fragmentada en distintos servicios."},{s:"AKIRA",t:"¿Entre sistemas diferentes? Eso significa que no es un error local. Alguien está coordinando esto."},{s:"LEO",t:"Sí. Como si cada fallo llevara una pieza. La cadena se construye completa solo cuando ocurren todos los eventos."},{s:"HANA",t:"Esto parece un mensaje distribuido. Está siendo dividido para pasar desapercibido. Necesitamos más datos para entender qué significa."},{s:"PANTALLA",t:"Reconstrucción automática: a7f3c9e8b1d4f6a2e9c7d3b0e5f1a8c4. Posibles interpretaciones: identificador interno desconocido, mensaje codificado personalizado, comando para activar acciones o parte de una operación más grande."},{s:"NARRADOR",t:"Cada pieza por separado parece inofensiva, pero juntas forman algo con un propósito claro."},{s:"NARRADOR",t:"Esto no es casualidad. Es un diseño."}],
[{s:"TÍTULO",t:"PÁGINA 31 — PIEZAS DE UN MENSAJE, UN PROPÓSITO OCULTO."},{s:"NARRADOR",t:"Los fragmentos del identificador se unen en una visualización global. El equipo observa cómo la información dispersa en distintos servicios forma un patrón coherente."},{s:"PANTALLA",t:"Reconstrucción del mensaje: a7f3c9e8 + b1d4f6a2 + e9c7d3b0 + e5f1a8c4. Mensaje reconstruido: EL SISTEMA ..."},{s:"SOFIA",t:"¿Eso estaba dentro de las respuestas?"},{s:"SOFIA",t:"Son datos reales del sistema. Nunca deberían incluir este tipo de mensaje."},{s:"HANA",t:"Alguien quería que lo encontráramos."},{s:"HANA",t:"No es un error ni un dato aleatorio. Esto fue colocado de manera deliberada."},{s:"PANTALLA",t:"Secuencia del mensaje: EL + SISTEMA + ... + FUNCIONA... Mensaje completo parcial: EL SISTEMA ... FUNCIONA..."},{s:"LEO",t:"El cuarto fragmento completa otra parte del mensaje. La secuencia indica que los fragmentos forman una sola frase. Aún falta el resto, pero el patrón es claro."},{s:"AKIRA",t:"Esto no es un accidente. Alguien diseñó esto para comunicarse. La pregunta es... ¿qué más viene en el mensaje?"},{s:"NOAH",t:"Si el mensaje dice ‘EL SISTEMA FUNCIONA...’, puede haber más instrucciones en los siguientes eventos."},{s:"NARRADOR",t:"Alguien conoce nuestros sistemas, nuestros tiempos y nuestra forma de trabajar."},{s:"NARRADOR",t:"Esto ya no es solo un ataque. Es un mensaje. Y puede tener un propósito más grande."},{s:"NARRADOR",t:"El sistema funciona... Pero ¿para quién? ¿Y con qué objetivo?"}],
[{s:"TÍTULO",t:"PÁGINA 32 — CLIFFHANGER: UN MENSAJE EN LA OSCURIDAD."},{s:"NARRADOR",t:"Durante años, NEXUS conectó al mundo."},{s:"NARRADOR",t:"Ese día, por primera vez, pareció responderle."},{s:"PANTALLA",t:"EL SISTEMA FUNCIONA..."},{s:"PANTALLA",t:">▌"},{s:"NARRADOR",t:"A veces, una respuesta es solo el comienzo."},{s:"RÓTULO",t:"CONTINUARÁ... Capítulo 2: 404."}]
];

const voiceProfiles={
'NARRADOR':{rate:.88,pitch:.90},'ESCENA':{rate:.92,pitch:.96},'RÓTULO':{rate:.88,pitch:.86},
'AKIRA':{rate:.98,pitch:.94},'MAYA':{rate:.94,pitch:1.08},'LEO':{rate:.97,pitch:.91},
'HANA':{rate:.91,pitch:1.02},'NOAH':{rate:.96,pitch:.90},'SOFIA':{rate:.93,pitch:1.10},
'SISTEMA':{rate:.82,pitch:.72},'PANTALLA':{rate:.86,pitch:.80},'OPERADOR':{rate:.94,pitch:.90},
'COMPAÑERO':{rate:.98,pitch:.97},'TÉCNICO':{rate:.95,pitch:.95},'COLEGA':{rate:.96,pitch:.93},
'ANALISTA':{rate:.94,pitch:.92},'USUARIA':{rate:.96,pitch:1.10}
};

const reader=document.querySelector('#reader'),pageImage=document.querySelector('#pageImage'),
pageLabel=document.querySelector('#pageLabel'),progress=document.querySelector('#progress'),
thumbs=document.querySelector('#thumbs'),stage=document.querySelector('#readerStage'),
scriptPanel=document.querySelector('#scriptPanel'),scriptText=document.querySelector('#scriptText'),
voiceStatus=document.querySelector('#voiceStatus');
let current=0,fitWidth=false,touchX=0,zoom=1;

function renderScript(){
  scriptText.innerHTML='';
  (scripts[current]||[]).forEach(line=>{
    const d=document.createElement('div');d.className='script-line';
    const sp=document.createElement('span');sp.className='speaker';sp.textContent=line.s+': ';
    const tx=document.createElement('span');tx.className=(line.s==='NARRADOR'||line.s==='ESCENA')?'narrator':'';tx.textContent=line.t;
    d.append(sp,tx);scriptText.appendChild(d);
  });
  document.querySelector('#scriptTitle').textContent=`Guion completo · página ${current+1}`;
}

function applyZoom(){
  const shell=document.querySelector('.page-shell');
  shell.style.setProperty('--zoom',zoom);
  document.querySelector('#zoomValue').textContent=`${Math.round(zoom*100)}%`;
  stage.classList.toggle('zoomed',zoom>1);
}
function render(){
  pageImage.src=pages[current];pageImage.alt=`TECH GUARDIANS — capítulo 1, página ${current+1}`;
  pageLabel.textContent=`Página ${current+1} de ${totalPages}`;
  progress.style.width=`${((current+1)/totalPages)*100}%`;
  document.querySelectorAll('.thumbs img').forEach((x,i)=>x.classList.toggle('active',i===current));
  document.querySelectorAll('.thumbs img')[current]?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});
  zoom=1;applyZoom();renderScript();
  document.querySelector('.page-scroll')?.scrollTo({top:0,left:0});
}
function openReader(){reader.classList.add('open');reader.setAttribute('aria-hidden','false');document.body.classList.add('reader-open');render();setTimeout(offerPage1Video,180);}
function closeReader(){closePageVideo();dismissVideoPrompt();page1VideoAsked=false;reader.classList.remove('open');reader.setAttribute('aria-hidden','true');document.body.classList.remove('reader-open');}
function go(n){current=Math.max(0,Math.min(totalPages-1,n));render();updatePageVideoButton();}

pages.forEach((src,i)=>{const im=new Image();im.src=src;im.alt=`Miniatura página ${i+1}`;im.loading='lazy';im.onclick=()=>go(i);thumbs.appendChild(im)});
['openReader','heroRead','cardRead'].forEach(id=>document.getElementById(id).onclick=openReader);
document.getElementById('closeReader').onclick=closeReader;
document.getElementById('prevPage').onclick=()=>go(current-1);document.getElementById('nextPage').onclick=()=>go(current+1);
document.getElementById('fitToggle').onclick=()=>{fitWidth=!fitWidth;stage.classList.toggle('fit-width',fitWidth);document.getElementById('fitToggle').textContent=fitWidth?'Página':'Ajustar ancho';zoom=1;applyZoom();document.querySelector('.page-scroll')?.scrollTo({top:0,left:0});};
document.getElementById('fullScreen').onclick=()=>{if(!document.fullscreenElement)reader.requestFullscreen?.();else document.exitFullscreen?.()};
document.getElementById('zoomIn').onclick=()=>{zoom=Math.min(3,zoom+.25);applyZoom()};
document.getElementById('zoomOut').onclick=()=>{zoom=Math.max(.5,zoom-.25);applyZoom()};
document.getElementById('zoomReset').onclick=()=>{zoom=1;applyZoom();document.querySelector('.page-scroll')?.scrollTo({top:0,left:0});};
pageImage.onclick=()=>{zoom=zoom===1?2:1;applyZoom();};
document.getElementById('toggleScript').onclick=()=>scriptPanel.hidden=!scriptPanel.hidden;
document.getElementById('closeScript').onclick=()=>scriptPanel.hidden=true;
document.addEventListener('keydown',e=>{if(!reader.classList.contains('open'))return;if(e.key==='ArrowRight'||e.key==='PageDown')go(current+1);if(e.key==='ArrowLeft'||e.key==='PageUp')go(current-1);if(e.key==='+'){zoom=Math.min(3,zoom+.25);applyZoom()}if(e.key==='-'){zoom=Math.max(.5,zoom-.25);applyZoom()}if(e.key==='Escape'&&!document.fullscreenElement)closeReader();});
stage.addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});
stage.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>55&&zoom===1)go(current+(d<0?1:-1))},{passive:true});

const videoPrompt=document.getElementById('videoPrompt');
const videoModal=document.getElementById('videoModal');
const pageVideo=document.getElementById('pageVideo');
let page1VideoAsked=false;

function offerPage1Video(){
  if(current!==0 || page1VideoAsked)return;
  page1VideoAsked=true;
  videoPrompt.hidden=false;
  videoPrompt.setAttribute('aria-hidden','false');
}
function dismissVideoPrompt(){
  videoPrompt.hidden=true;
  videoPrompt.setAttribute('aria-hidden','true');
}
function openPageVideo(){
  dismissVideoPrompt();
  videoModal.hidden=false;
  videoModal.setAttribute('aria-hidden','false');
  pageVideo.currentTime=0;
  pageVideo.play().catch(()=>{});
}
function closePageVideo(){
  pageVideo.pause();
  videoModal.hidden=true;
  videoModal.setAttribute('aria-hidden','true');
}


// v8: controles del lector inicializados antes del primer render.
const pageVideos={0:'https://youtu.be/b6xK96FcaoI',1:'https://youtu.be/lPzLLjLngvQ'};
const openPageVideoBtn=document.getElementById('openPageVideoBtn');
const backHomeBtn=document.getElementById('backHomeBtn');

function updatePageVideoButton(){
  if(!openPageVideoBtn)return;
  const available=Boolean(pageVideos[current]);
  openPageVideoBtn.disabled=!available;
  openPageVideoBtn.textContent=available?'▶ Video':'▶ Sin video';
  openPageVideoBtn.title=available?'Ver video de esta página':'Esta página todavía no tiene video';
}

function playCurrentPageVideo(){
  const url=pageVideos[current];
  if(!url)return;
  window.open(url,'_blank','noopener,noreferrer');
}

function goToHome(){
  try{
    if(pageVideo)pageVideo.pause();
  }catch(e){}
  // Navegación real al documento principal, funciona en GitHub Pages y servidor web.
  window.location.href='./index.html';
}

if(openPageVideoBtn)openPageVideoBtn.addEventListener('click',playCurrentPageVideo);
if(backHomeBtn)backHomeBtn.addEventListener('click',goToHome);

document.getElementById('playPageVideo').onclick=playCurrentPageVideo;
document.getElementById('continueManga').onclick=dismissVideoPrompt;
document.getElementById('closeVideoPrompt').onclick=dismissVideoPrompt;
document.getElementById('closePageVideo').onclick=closePageVideo;
videoPrompt.addEventListener('click',e=>{if(e.target===videoPrompt)dismissVideoPrompt();});
videoModal.addEventListener('click',e=>{if(e.target===videoModal)closePageVideo();});
pageVideo.addEventListener('ended',closePageVideo);

render();
updatePageVideoButton();
